name: Deploy Update

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Sync Files via Rsync
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # Mengecualikan folder krusial agar tidak ditimpa/dihapus dari server
          ARGS: "-avzr --delete --exclude='.git/' --exclude='.env' --exclude='storage/' --exclude='vendor/' --exclude='node_modules/'"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          REMOTE_PORT: ${{ secrets.SSH_PORT }}
          # GANTI 'aplikasi_laravel' DENGAN NAMA FOLDER APLIKASI ANDA DI HOSTING
          TARGET: "/home/${{ secrets.SSH_USERNAME }}/domains/development-agt.web.id/public_html/penjualan-tenant"

      - name: Run Artisan Optimization via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # GANTI 'aplikasi_laravel' DENGAN NAMA FOLDER APLIKASI ANDA
            cd /home/${{ secrets.SSH_USERNAME }}/aplikasi_laravel
            
            php artisan down
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan filament:cache-components
            php artisan up
